spring:
  data:
    mongodb:
      host: localhost
      database: Chat_Astro
      port: 27017
      repositories:
        enabled: true
  session:
    store-type: MongoDB

website:
  address: astro.ski

server:
  servlet:
    context-path: /api
