version: "3.7"

services:
  core:
    build: .
    ports:
      - 9090:9090
    depends_on:
      - mongodb
      - rabbitmq
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3.5.3-management
    container_name: rabbitmq
    environment:
        - RABBITMQ_DEFAULT_USER=user
        - RABBITMQ_DEFAULT_PASS=user

    command: sh -c "rabbitmq-plugins enable rabbitmq_stomp"
    ports:
      - 5672:5672
      - 61613:61613